In [3]:
import numpy as np

In [4]:
A = np.array([1, 2, 3, 4])
print(A)
np.ndim(A)

[1 2 3 4]


1

In [5]:
A.shape

(4,)

In [6]:
B = np.array([[1,2], [3,4], [5,6]])

print(B)
np.ndim(B)

[[1 2]
 [3 4]
 [5 6]]


2

## 3.3.2 行列の積

- 行列の積(内積)は`np.dot()`で計算できる
- 行列の積は被演算子の順序が異なると結果が変わる(非可換)
- 行列の積を計算するには、対応する次元の要素数が一致している必要がある
  - 1次元目の要素数(列数)と行列Bの

In [7]:
A = np.array([[1,2], [3,4]])
print(f'A.shape: {A.shape}')

B = np.array([[5,6], [7,8]])
print(f'B.shape: {B.shape}')

np.dot(A, B)

A.shape: (2, 2)
B.shape: (2, 2)


array([[19, 22],
       [43, 50]])

In [8]:
A = np.array([[1,2,3], [4,5,6]])
print(f'A.shape: {A.shape}')

B = np.array([[1,2], [3,4], [5,6]])
print(f'B.shape: {B.shape}')

np.dot(A, B)

A.shape: (2, 3)
B.shape: (3, 2)


array([[22, 28],
       [49, 64]])

In [9]:
X = np.array([1, 2])
print(X.shape)

# x1_w = [1,3,5]
# x2_w = [2,4,6]
W = np.array([[1,3,5], [2,4,6]])
print(W)

W.shape

Y = np.dot(X, W)
print(f'Y: {Y}')

(2,)
[[1 3 5]
 [2 4 6]]
Y: [ 5 11 17]


## 3層ニューラルネットワークの実装

$$
    a^{(1)}_n = w^{(1)}_{11}x_1 + w^{(1)}_{12}x_2 + b^{(1)}_1
$$

上記の式は行列式で以下のように表せる

$$
\begin{align}
    \mathbf{A}^{(1)} = \mathbf{X}\mathbf{W}^{(1)} + \mathbf{B}^{(1)} \\
    \mathbf{A}^{(1)}  
\end{align}
$$

In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([-1., 1., 2.])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

In [11]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(f'W1.shape: {W1.shape}')
print(f'X.shape: {X.shape}')
print(f'B1.shape: {B1.shape}')

A1 = np.dot(X, W1) + B1

print(A1)

W1.shape: (2, 3)
X.shape: (2,)
B1.shape: (3,)
[0.3 0.7 1.1]


In [ ]:
# 隠れそうでの重み付き和

# 活性化関数により変換された信号
Z1 = sigmoid(A1)

print(A1)
print(Z1)

## 第1層から第2層の実装(図3-19)


In [ ]:
# 第二層の重みとバイアスの定義
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([.1, .2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

In [ ]:
# 第2層の入力値の定義
# => 第一層の出力Z1と、重みW2にバイアスB2を足したもの(=Z1の重み付き線形和)
A2 = np.dot(Z1, W2) + B2

# 第二層の出力値を定義
# => 第二層の入力値に活性化関数を適用したもの
Z2 = sigmoid(A2)

print(f'A2: {A2}')
print(f'Z2: {Z2}')

# 最終層(第3層)の実装(図3-20)


In [ ]:
def identity_function(x):
    """Returns the inputs as is

    Parameters:
    ---
    x: np.array<T>

    Returns:
    ---
    np.array<T>
    """

    return x

In [ ]:
W3 = np.array([[.1, .3], [.2, .4]])
B3 = np.array([.1, .2])

# 入力値を定義(第二層の重み付き線形和)
A3 = np.dot(Z2, W3) + B3
print(f'A3: {A3}')

# 最終出力を定義
Y = identity_function(A3)

print(f'output Y: {Y}')

- 出力層で利用する活性化関数は解く問題の性質に応じて決定する
- 以下のような例が一般的
    - 回帰問題では恒等関数
    - 2クラス分類ではシグモイド関数
    - 多クラス分類ではソフトマックス関数など

# 3.4.3 実装のまとめ

In [ ]:
# ネットワークの初期化
def init_network():
    """ Initialize the networks

    Parameters:
    ---
    None

    Returns:
    ---
    dict(np.array[<T>]
        initialized network
    """

    network= {}

    # 各層の重みとバイアスを定義
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    """ Define the forward sequence

    Parameters:
    ---
    dict(np.array)
        network: weighted network
    np.array:
        x: inputs

    Returns:
    ---
    np.array
        outputs of the network
    """

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)

    # a2 = np.dot(z1, W2) + b2
    # 2次元行列の積はnp.matmul()でもでもnp.dot()と等価
    # ただし, 3次元以上の積の場合は, np.dot()と振る舞いが異なるので注意
    a2 = np.matmul(z1, W2) + b2

    z2 = sigmoid(a2)

    # a3 = np.dot(z2, W3) + b3
    # np.matmul()は@演算子でも書ける(>=Python3.5 && >=Numpy1.10.0 )
    a3 = z2 @ W3 + b3
    
    y = identity_function(a3)
    # print(f'a3: {a3}, y: {y}')

    return y

In [ ]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)

print(y)