In [5]:
import sys
import os
from pathlib import Path

# importディレクトリの追加
# sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
print(sys.path)

# プロキシの設定
# os.environ['HTTP_PROXY'] = ''
# os.environ['HTTPS_PROXY'] = ''

%matplotlib inline

['/home/y-katayama/notebooks', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '', '/home/y-katayama/venv/pt1.7/lib/python3.8/site-packages']


In [6]:
!nvidia-smi

Tue Dec  6 10:41:05 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 40%   32C    P8    17W / 184W |     47MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:03:00.0 Off |                  N/A |
| 40%   

In [7]:
import torch
import numpy as np

## テンソルの初期化

In [25]:
# リストから直接テンソルを作る
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print({x_data})

# Numpy Arrayからテンソルを作る
np_array = np.array([[4,3], [2,1]])
x_np = torch.from_numpy(np_array)
print(x_np)

# x_dataの形状を維持してテンソルを作る
x_ones = torch.ones_like(x_data)
print(x_ones)

# x_dataのdatatypeを上書き更新する
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

{tensor([[1, 2],
        [3, 4]])}
tensor([[4, 3],
        [2, 1]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.2309, 0.6264],
        [0.9460, 0.6480]])


# ランダム値や定数テンソル作成

In [27]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'rand_tensor: {rand_tensor}')
print(f'ones_tensor: {ones_tensor}')
print(f'zeros_tensor: {zeros_tensor}')

rand_tensor: tensor([[0.6031, 0.0320, 0.6998],
        [0.3789, 0.0235, 0.1074]])
ones_tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


# テンソルの属性

- テンソルは属性変数として, 以下を保持している
  - 形状(shape)
  - データ型(dtype)
  - 保存されているデバイス(device)

In [28]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# テンソルの操作

- テンソルはdefaultではCPU上にt区られる
- テンソルは`.to()`を使用して, 任意のデバイスに移動させることができる
- 大きなテンソルをデバイス間でコピーすると, 時間とメモリ面でのコストがかかる

In [30]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(tensor)

tensor([[0.7189, 0.4346, 0.8713, 0.8511],
        [0.8774, 0.0375, 0.6056, 0.8145],
        [0.6037, 0.2918, 0.8418, 0.8067]], device='cuda:0')


## Numpy-likeなindexingとslicing

In [36]:
tensor = torch.ones(4, 4)
# 1行目のテンソルを表示
print(f'first row: {tensor[0]}')

# 1列目のテンソルを表示
print(f'first col: {tensor[:, 0]}')

# 最終列のテンソルを表示
print(f'last col: {tensor[..., -1]}')

# 2列目に0を代入
tensor[:, 1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.])
first col: tensor([1., 1., 1., 1.])
last col: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## テンソルの結合

In [47]:
# torch.cat()は横方向に連結する
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

# torch.stack()は縦方向に連結する
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


## 算術演算

- 行列の内積は`@オペレータ`か`matmul()`で求められる
- 行列の要素ごとの積(アダマール積)は`*オペレータ`, `mul()`で求められる

In [55]:
# 内積を計算
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


print(f'y1: {y1}')
print(f'y2: {y2}')
print(f'y3: {y3}')

# アダマール積を計算
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f'z1: {z1}')
print(f'z2: {z2}')
print(f'z3: {z3}')

y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 1要素のテンソル

- 1要素のテンソルは`.item()`を使用して数値型に変換できる

In [59]:
# item()で数値型変換できる
print(tensor)

# 全要素の総和 = 12
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
12.0 <class 'float'>


## インプレース操作

- 演算結果をオペランドに格納する操作をインプレースと呼ぶ
- インプレース操作はメソッドの接頭辞に`_`が付く
  - `x.copy_()`や`x.t_()`等

  
- インプレース操作はメモリを節約できるが, 演算履歴が失われるため, 微分計算の際に問題となる

- **微分を求める場合, インプレース操作は非推奨**

# Numpyとの変換

- torch.Tensorは`.numpy()`を使用してNumpy配列に変換できる
- 変換したオブジェクトは同じメモリを共有している
    - 元のテンソルが変化するとNumpy側も, 変化が反映される
    - これはNumpyからTensorに変換する場合も同じ

In [61]:
t = torch.ones(5)
print(f't: {t}')

n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [62]:
# 元のテンソルの値を変更
t.add_(1)

# 変換後のNump
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
